=== servicosgoval/cartas-de-servico/backup/v2/servico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://servicos.gov.br/cartas-servico/v2/schema/servico"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">

    <xs:element name="servico">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nome" minOccurs="1" maxOccurs="1" type="nome"/>
                <xs:element name="nomes-populares" minOccurs="1" maxOccurs="1" type="texto-curto"/>
                <xs:element name="descricao" minOccurs="1" maxOccurs="1" type="texto-longo"/>
                <xs:element name="palavras-chave" minOccurs="1" maxOccurs="1" type="texto-curto"/>

                <xs:element name="areas-de-interesse" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="area-de-interesse">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="area" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="segmentos-da-sociedade" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="segmento-da-sociedade">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="nome" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="eventos-da-linha-da-vida" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="evento-da-linha-da-vida">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="nome" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="legislacao-relacionada" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="link">
                                <xs:complexType>
                                    <xs:attribute name="href" type="xs:anyURI"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="solicitantes" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="solicitante" type="texto-curto"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="tempo-total-estimado" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="minimo" minOccurs="0" maxOccurs="1" type="unidade-de-tempo-estimado"/>
                            <xs:element name="maximo" type="unidade-de-tempo-estimado"/>
                            <xs:element name="excecoes" type="texto-longo"/>
                        </xs:all>

                        <xs:attribute name="tipo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="até"/>
                                    <xs:enumeration value="entre"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="etapas" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="etapa">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="titulo" type="texto-curto"/>
                                        <xs:element name="descricao" type="texto-longo"/>

                                        <xs:element name="documentos">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="documento" type="texto-curto"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="custos">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="custo">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="descricao" type="texto-curto"/>
                                                                <xs:element name="valor" type="valor"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="excecoes" type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="canais-de-prestacao">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="canal-de-prestacao">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:sequence>
                                                                    <xs:element name="titulo" type="texto-curto"/>
                                                                    <xs:element name="referencia" type="xs:string"/>
                                                                </xs:sequence>
                                                                <xs:sequence>
                                                                    <xs:element name="descricao" type="texto-curto"/>
                                                                </xs:sequence>
                                                            </xs:choice>
                                                            <xs:attribute name="tipo">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="Agendamento"/>
                                                                        <xs:enumeration value="Web"/>
                                                                        <xs:enumeration value="Presencial"/>
                                                                        <xs:enumeration value="Telefone"/>
                                                                        <xs:enumeration value="E-mail"/>
                                                                        <xs:enumeration value="Caixa postal"/>
                                                                        <xs:enumeration value="Aplicativo móvel"/>
                                                                        <xs:enumeration value="SMS"/>
                                                                        <xs:enumeration value="Fax"/>
                                                                        <xs:enumeration value="Rede social"/>
                                                                        <xs:enumeration value="Outros"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="preferencial" type="xs:boolean"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="orgao" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="id" type="id"/>
                            <xs:element name="nome" type="texto-curto"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>

                <xs:element name="gratuito" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"/>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="situacao" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>

            <xs:attribute name="versao" fixed="2"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="unidade-de-tempo-estimado">
        <xs:simpleContent>
            <xs:extension base="texto-curto">
                <xs:attribute name="tipo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="minutos"/>
                            <xs:enumeration value="horas"/>
                            <xs:enumeration value="dias"/>
                            <xs:enumeration value="dias corridos"/>
                            <xs:enumeration value="dias úteis"/>
                            <xs:enumeration value="meses"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="nome">
        <xs:restriction base="texto-curto">
            <xs:maxLength value="151"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto-curto">
        <xs:restriction base="xs:string">
            <xs:maxLength value="300"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto-longo">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="id">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:pattern value="[a-z-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="valor">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d+(,\d\d)?)?"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/acesso-ao-sped-sistema-publico-de-escrituracao-digital.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Acesso ao Sped - Sistema Público de Escrituração Digital
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Instituído pelo Decreto nº 6.022, de 22 de janeiro de 2007, o Sistema Público de Escrituração Digital (Sped) faz parte do Programa de Aceleração do Crescimento do Governo Federal (PAC 2007-2010) e constitui-se em mais um avanço na informatização da relação entre o fisco e os contribuintes.

De modo geral, consiste na modernização da sistemática atual do cumprimento das obrigações acessórias, transmitidas pelos contribuintes às administrações tributárias e aos órgãos fiscalizadores, utilizando-se da certificação digital para fins de assinatura dos documentos eletrônicos, garantindo assim a validade jurídica dos mesmos apenas na sua forma digital.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    empresas
   </id>
   <nome>
    Empresas
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    empreendedorismo-e-negocios
   </id>
   <nome>
    Empreendedorismo e negócios
   </nome>
  </evento-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    contas-e-impostos
   </id>
   <nome>
    Contas e Impostos
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://www.receita.fazenda.gov.br/Sped/Download/Default.htm
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/cadastro-de-procuracao-para-o-portal-e-cac-presencial.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Cadastro de Procuração para o Portal e-CAC – Presencial
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Cadastrar, consultar e cancelar procuração, que delega a terceiro, possuidor de certificado digital, a
        realização de serviços dentro do portal e-CAC. Não há necessidade de o outorgante possuir certificado digital
        para constituir a procuração. No caso do cadastro e cancelamento, o documento impresso deve ser entregue na
        unidade de atendimento presencial, conforme orientações gerais. Não há necessidade de o outorgante possuir
        certificado digital para constituir a procuração.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
  <segmento-da-sociedade>
   <id>
    empresas
   </id>
   <nome>
    Empresas
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida></eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://www.receita.fazenda.gov.br/Aplicacoes/ATSDR/procuracoesrfb/controlador/controlePrincipal.asp?acao=telaInicial
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/consulta-obras-do-ministerio-do-turismo-em-seu-municipio.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Consulta - Obras do Ministério do Turismo em seu Município
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Consulta ao andamento dos contratos de repasse referente a obras de infraestrutura turística nos municípios.

* Mais informações sobre o andamento de cada obra podem ser obtidas via Sistema de Informações ao Cidadão (SIC): sic@turismo.gov.br, ou (61) 2023-7146
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    comercio-e-servicos
   </id>
   <area>Comércio e Serviços</area>
  </area-de-interesse>
  <area-de-interesse>
   <id>
    turismo
   </id>
   <area>Turismo</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida></eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://repasse.turismo.gov.br/
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-do-turismo-mtur
  </id>
  <nome>
   Ministério do Turismo (MTur)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/aposentadoria-por-idade.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Aposentadoria por Idade
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Benefício devido aos trabalhadores urbanos do sexo masculino a partir dos 65 anos e do sexo feminino a partir dos 60 anos de idade. Os trabalhadores rurais podem pedir aposentadoria por idade com cinco anos a menos: a partir dos 60 anos, homens, e a partir dos 55 anos, mulheres.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    previdencia-social
   </id>
   <area>Previdência Social</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    aposentadoria
   </id>
   <nome>
    Aposentadoria
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
      http://www2.dataprev.gov.br/prevagenda/OpcaoInicialTela.view
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-da-previdencia-social-mps
  </id>
  <nome>
   Ministério da Previdência Social (MPS)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/portal-do-professor.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Portal do Professor
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>O Portal do Professor, acessível on-line desde 2008, em parceria com o Ministério da Ciência, Tecnologia e Inovação, apoia os processos de formação dos professores brasileiros e ajuda a enriquecer a prática pedagógica. No portal, os profissionais da educação podem produzir e compartilhar sugestões de aulas; buscar informações diversas sobre a prática educacional; baixar coleções de recursos multimídia; obter informações sobre cursos e material de estudos; interagir e colaborar com outros professores.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    educacao
   </id>
   <area>Educação</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade></segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    profissao-e-trabalho
   </id>
   <nome>
    Profissão e trabalho
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://portaldoprofessor.mec.gov.br/sobre.html
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-da-educacao-mec
  </id>
  <nome>
   Ministério da Educação (MEC)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/opcoes-da-lei-n-11-941-2009.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Opções da Lei nº 11.941/2009
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Imprimir Darf para pagamentos das prestações, acompanhar a situação dos pedidos, emitir recibos de adesão e consultar deferimento do requerimento de adesão às modalidades de parcelamento e pagamento à vista da Lei nº 11.941, de 27 de maio de 2009.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade></segmentos-da-sociedade>
 <eventos-da-linha-da-vida></eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      https://cav.receita.fazenda.gov.br/eCAC/publico/login.aspx?sistema=00039
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>
