=== servicosgoval/cartas-de-servico/backup/v2/servico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://servicos.gov.br/cartas-servico/v2/schema/servico"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">

    <xs:element name="servico">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nome" minOccurs="1" maxOccurs="1" type="nome"/>
                <xs:element name="nomes-populares" minOccurs="1" maxOccurs="1" type="texto-curto"/>
                <xs:element name="descricao" minOccurs="1" maxOccurs="1" type="texto-longo"/>
                <xs:element name="palavras-chave" minOccurs="1" maxOccurs="1" type="texto-curto"/>

                <xs:element name="areas-de-interesse" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="area-de-interesse">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="area" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="segmentos-da-sociedade" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="segmento-da-sociedade">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="nome" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="eventos-da-linha-da-vida" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="evento-da-linha-da-vida">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="nome" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="legislacao-relacionada" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="link">
                                <xs:complexType>
                                    <xs:attribute name="href" type="xs:anyURI"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="solicitantes" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="solicitante" type="texto-curto"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="tempo-total-estimado" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="minimo" minOccurs="0" maxOccurs="1" type="unidade-de-tempo-estimado"/>
                            <xs:element name="maximo" type="unidade-de-tempo-estimado"/>
                            <xs:element name="excecoes" type="texto-longo"/>
                        </xs:all>

                        <xs:attribute name="tipo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="até"/>
                                    <xs:enumeration value="entre"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="etapas" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="etapa">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="titulo" type="texto-curto"/>
                                        <xs:element name="descricao" type="texto-longo"/>

                                        <xs:element name="documentos">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="documento" type="texto-curto"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="custos">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="custo">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="descricao" type="texto-curto"/>
                                                                <xs:element name="valor" type="valor"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="excecoes" type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="canais-de-prestacao">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="canal-de-prestacao">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:sequence>
                                                                    <xs:element name="titulo" type="texto-curto"/>
                                                                    <xs:element name="referencia" type="xs:string"/>
                                                                </xs:sequence>
                                                                <xs:sequence>
                                                                    <xs:element name="descricao" type="texto-curto"/>
                                                                </xs:sequence>
                                                            </xs:choice>
                                                            <xs:attribute name="tipo">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="Agendamento"/>
                                                                        <xs:enumeration value="Web"/>
                                                                        <xs:enumeration value="Presencial"/>
                                                                        <xs:enumeration value="Telefone"/>
                                                                        <xs:enumeration value="E-mail"/>
                                                                        <xs:enumeration value="Caixa postal"/>
                                                                        <xs:enumeration value="Aplicativo móvel"/>
                                                                        <xs:enumeration value="SMS"/>
                                                                        <xs:enumeration value="Fax"/>
                                                                        <xs:enumeration value="Rede social"/>
                                                                        <xs:enumeration value="Outros"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="preferencial" type="xs:boolean"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="orgao" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="id" type="id"/>
                            <xs:element name="nome" type="texto-curto"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>

                <xs:element name="gratuito" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"/>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="situacao" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>

            <xs:attribute name="versao" fixed="2"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="unidade-de-tempo-estimado">
        <xs:simpleContent>
            <xs:extension base="texto-curto">
                <xs:attribute name="tipo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="minutos"/>
                            <xs:enumeration value="horas"/>
                            <xs:enumeration value="dias"/>
                            <xs:enumeration value="dias corridos"/>
                            <xs:enumeration value="dias úteis"/>
                            <xs:enumeration value="meses"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="nome">
        <xs:restriction base="texto-curto">
            <xs:maxLength value="151"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto-curto">
        <xs:restriction base="xs:string">
            <xs:maxLength value="300"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto-longo">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="id">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:pattern value="[a-z-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="valor">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d+(,\d\d)?)?"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/seguro-desemprego.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Seguro-Desemprego
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Seguro-Desemprego Formal: Seguro-desemprego ao trabalhador formal possui como finalidade: prover assistência financeira temporária a trabalhadores desempregados sem justa causa e auxiliá-los na busca de um novo emprego, por meio de orientação, recolocação no mercado de trabalho e/ou qualificação profissional.

Seguro-Desemprego Pescador Artesanal: É dirigido ao pescador profissional que exerça sua atividade de forma artesanal, individual ou em regime de economia familiar, ainda que com auxílio eventual de parceiros e que teve que interromper a atividade pesqueira devido ao período de proibição da pesca, para preservação da espécie (defeso), fixado através de Instrumento Normativo publicado no Diário Oficial da União.

Seguro-Desemprego Empregado Doméstico: Trata-se de ação que resulta em pagamento do benefício instituído pela Lei n.º 10.208, de 23 de março de 2001, tem por finalidade prover assistência financeira temporária ao empregado doméstico dispensado sem justa causa. O valor de cada parcela é de um salário mínimo, sendo que cada segurado recebe no máximo três parcelas. Com a aprovação da Emenda Constitucional nº 72, de 2 de abril de 2013, houve equiparação de direitos trabalhistas entre o doméstico e demais trabalhadores, entretanto, necessita-se de regulamentação quanto a percepção igualitária de parcelas inerentes ao seguro-desemprego.

Seguro-Desemprego Trabalhador Resgatado: É um auxílio temporário concedido ao trabalhador comprovadamente resgatado de regime de trabalho forçado ou da condição análoga à de escravo. Tendo direito a no máximo três parcelas no valor de um salário mínimo.

Seguro-Desemprego Bolsa Qualificação: A Bolsa de Qualificação Profissional é um benefício destinado a subvencionar os trabalhadores com contrato de trabalho suspenso, em conformidade com o disposto em convenção ou acordo coletivo de trabalho, devidamente matriculado em curso ou programa de qualificação profissional oferecido pelo empregador.

* [Consulta: Habilitação do Seguro-Desemprego](http://granulito.mte.gov.br/sdweb/consulta.jsf)
* [Modalidade de Seguro-Desemprego Empregado Doméstico](http://portal.mte.gov.br/seg_desemp/seguro-desemprego-trabalhador-domestico.htm)
* [Modalidade de Seguro-Desemprego Pescador Artesanal](http://portal.mte.gov.br/seg_desemp/seguro-desemprego-pescador-artesanal.htm)
* [Modalidade Seguro-Desemprego Trabalhador Resgatado](http://portal.mte.gov.br/seg_desemp/modalidades-seguro-desemprego-empregado-resgatado.htm)
* [Modalidade de Seguro-Desemprego Formal](http://portal.mte.gov.br/seg_desemp/seguro-desemprego-formal-2.htm)
* [Bolsa Qualificação](http://portal.mte.gov.br/seg_desemp/bolsa-qualificacao.htm)
* Coordenação-Geral do Seguro-Desemprego: (61) 2031-6679 Pescador Artesanal: (61) 2031-6043/6973 Empregado Doméstico/Trabalhador Resgatado: (61) 2031-6135/6226 Bolsa Qualificação: (61) 2031-6196/6509
* [Postos de atendimento do Ministério do Trabalho e Emprego](http://portal.mte.gov.br/postos/)
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    trabalho
   </id>
   <area>Trabalho</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    apoio-financeiro-e-credito
   </id>
   <nome>
    Apoio financeiro e crédito
   </nome>
  </evento-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    profissao-e-trabalho
   </id>
   <nome>
    Profissão e trabalho
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-do-trabalho-e-emprego-mte
  </id>
  <nome>
   Ministério do Trabalho e Emprego (MTE)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/salario-familia.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Salário-Família
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Fornece informações sobre o Salário-Família e documentos necessários para solicitação do benefício em uma Agência da Previdência Social.

* Ligue 135 para obter maiores informações.
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    previdencia-social
   </id>
   <area>Previdência Social</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    familia
   </id>
   <nome>
    Família
   </nome>
  </evento-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    profissao-e-trabalho
   </id>
   <nome>
    Profissão e trabalho
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://agencia.previdencia.gov.br/e-aps/servico/376
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-da-previdencia-social-mps
  </id>
  <nome>
   Ministério da Previdência Social (MPS)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/acesso-aos-acervos-da-fundacao-nacional-do-indio-funai.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Acesso aos Acervos da Fundação Nacional do Índio - FUNAI
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>A Fundação Nacional do Índio - FUNAI - tem como missão coordenar o processo de formulação e implementação da política indigenista do Estado brasileiro, instituindo mecanismos efetivos de controle social e de gestão participativa, visando à proteção e promoção dos direitos dos povos indígenas.

Os atendimentos oferecidos aos cidadãos pela FUNAI relativos ao acesso aos seus acervos são:

- Acesso aos acervos arquivísticos (documentais) do fundo Serviço de Proteção ao Índio - SPI e aos acervos do período Funai, via Serviço de Gestão Documental – Brasília, e Serviço de Referências Documentais do Museu do Índio – Rio de Janeiro;

- Acesso aos acervos bibliográficos sobre a temática indígena, ambiental e indigenista, no Serviço de Gestão de Bibliotecas – Brasília, e Biblioteca do Museu do Índio – Rio de Janeiro e;

- Acesso aos acervos etnográficos e audiovisuais – Serviço de Referências Documentais do Museu do Índio – Rio de Janeiro.

* [Lei nº 12.527/11](http://www.planalto.gov.br/ccivil_03/_Ato2011-2014/2011/Lei/L12527.htm)
* Para Acervos Arquivísticos (documentais): sedoc@funai.gov.br (Serviço de Gestão Documental) ou referencia.documental@museudoindio.gov.br (Museu do Índio)
* Para Acervos Bibliograficos: sebib@funai.gov.br
* Para Acervos Etnográficos e Audiovisuais : referencia.documental@museudoindio.gov.br
* Para Acesso aos Acervos Etnográficos e Audiovisuais: (21)3214-8736.
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    protecao-social
   </id>
   <area>Proteção social</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade></segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    estudos
   </id>
   <nome>
    Estudos
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://base2.museudoindio.gov.br
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-da-justica-mj
  </id>
  <nome>
   Ministério da Justiça (MJ)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/cadastramento-de-senha-para-envio-de-demonstrativos-e-comprovante-de-repasse-previdenciarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Cadastramento de Senha para envio de Demonstrativos e Comprovante de Repasse Previdenciários
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Tem como objetivo liberar senha para os representantes legais dos entes federativos, da Unidade Gestora e de seus servidores para o envio de demonstrativos e comprovante de repasse, visualização de CRP de todos os municípios de um estado e consultas relativas a aplicações e investimentos.

* Ligue 135 para obter mais informações.
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    previdencia-social
   </id>
   <area>Previdência Social</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    empresas
   </id>
   <nome>
    Empresas
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida></eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://www1.previdencia.gov.br/sps/app/controleAcesso/cAcesso_login.asp?destino=CR
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-da-previdencia-social-mps
  </id>
  <nome>
   Ministério da Previdência Social (MPS)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/emissao-de-certidao-previdenciaria-certidao-contribuicoes-previdenciarias-certidoes-e-situacao-fiscal.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Emissão de Certidão Previdenciária (Certidão Contribuições Previdenciárias / Certidões e Situação Fiscal)
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Solicitar a emissão de certidão de contribuições previdenciárias. A certidão para fins de averbação de imóvel é emitida somente nas unidades de atendimento presencial. A Declaração de Regularidade de Situação do Contribuinte Individual – DRS-CI deve ser solicitada no INSS.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
  <segmento-da-sociedade>
   <id>
    empresas
   </id>
   <nome>
    Empresas
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    contas-e-impostos
   </id>
   <nome>
    Contas e Impostos
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://hom.receita.fazenda.gov.br/aplicacoes/atbhe/tus/Servico.aspx?id=182&amp;idArea=3&amp;idAssunto=39
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>
