=== servicosgoval/cartas-de-servico/backup/v2/servico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://servicos.gov.br/cartas-servico/v2/schema/servico"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">

    <xs:element name="servico">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nome" minOccurs="1" maxOccurs="1" type="nome"/>
                <xs:element name="nomes-populares" minOccurs="1" maxOccurs="1" type="texto-curto"/>
                <xs:element name="descricao" minOccurs="1" maxOccurs="1" type="texto-longo"/>
                <xs:element name="palavras-chave" minOccurs="1" maxOccurs="1" type="texto-curto"/>

                <xs:element name="areas-de-interesse" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="area-de-interesse">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="area" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="segmentos-da-sociedade" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="segmento-da-sociedade">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="nome" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="eventos-da-linha-da-vida" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="evento-da-linha-da-vida">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="id" type="id"/>
                                        <xs:element name="nome" type="texto-curto"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="legislacao-relacionada" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="link">
                                <xs:complexType>
                                    <xs:attribute name="href" type="xs:anyURI"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="solicitantes" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="solicitante" type="texto-curto"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="tempo-total-estimado" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="minimo" minOccurs="0" maxOccurs="1" type="unidade-de-tempo-estimado"/>
                            <xs:element name="maximo" type="unidade-de-tempo-estimado"/>
                            <xs:element name="excecoes" type="texto-longo"/>
                        </xs:all>

                        <xs:attribute name="tipo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="até"/>
                                    <xs:enumeration value="entre"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="etapas" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="etapa">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="titulo" type="texto-curto"/>
                                        <xs:element name="descricao" type="texto-longo"/>

                                        <xs:element name="documentos">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="documento" type="texto-curto"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="custos">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="custo">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="descricao" type="texto-curto"/>
                                                                <xs:element name="valor" type="valor"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="excecoes" type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="canais-de-prestacao">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                                                    <xs:element name="canal-de-prestacao">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:sequence>
                                                                    <xs:element name="titulo" type="texto-curto"/>
                                                                    <xs:element name="referencia" type="xs:string"/>
                                                                </xs:sequence>
                                                                <xs:sequence>
                                                                    <xs:element name="descricao" type="texto-curto"/>
                                                                </xs:sequence>
                                                            </xs:choice>
                                                            <xs:attribute name="tipo">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="Agendamento"/>
                                                                        <xs:enumeration value="Web"/>
                                                                        <xs:enumeration value="Presencial"/>
                                                                        <xs:enumeration value="Telefone"/>
                                                                        <xs:enumeration value="E-mail"/>
                                                                        <xs:enumeration value="Caixa postal"/>
                                                                        <xs:enumeration value="Aplicativo móvel"/>
                                                                        <xs:enumeration value="SMS"/>
                                                                        <xs:enumeration value="Fax"/>
                                                                        <xs:enumeration value="Rede social"/>
                                                                        <xs:enumeration value="Outros"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="preferencial" type="xs:boolean"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="orgao" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="id" type="id"/>
                            <xs:element name="nome" type="texto-curto"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>

                <xs:element name="gratuito" minOccurs="0" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"/>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="situacao" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>

            <xs:attribute name="versao" fixed="2"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="unidade-de-tempo-estimado">
        <xs:simpleContent>
            <xs:extension base="texto-curto">
                <xs:attribute name="tipo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="minutos"/>
                            <xs:enumeration value="horas"/>
                            <xs:enumeration value="dias"/>
                            <xs:enumeration value="dias corridos"/>
                            <xs:enumeration value="dias úteis"/>
                            <xs:enumeration value="meses"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="nome">
        <xs:restriction base="texto-curto">
            <xs:maxLength value="151"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto-curto">
        <xs:restriction base="xs:string">
            <xs:maxLength value="300"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="texto-longo">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="id">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:pattern value="[a-z-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="valor">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d+(,\d\d)?)?"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/requerimento-para-prioridade-no-pagamento-de-restituicao-de-imposto-de-renda.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Requerimento para Prioridade no Pagamento de Restituição de Imposto de Renda
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Requerer prioridade no pagamento de restituição do imposto de renda da pessoa física (art. 69-A da Lei nº 9.784/99).


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    contas-e-impostos
   </id>
   <nome>
    Contas e Impostos
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      https://www.google.com.br/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;cad=rja&amp;uact=8&amp;ved=0CB4QFjAA&amp;url=http%3A%2F%2Fwww.receita.fazenda.gov.br%2Fpublico%2Fformularios%2FRequerimento_Prioridade_Pgto_Restituicao_PF.doc&amp;ei=S_VQVajiLcHAggSJhIDACQ&amp;usg=AFQjCNEbEB7b5AHTaZzFKZAVT4Yi-SM_Lg&amp;sig2=YaZqZY9-8ctC34eMF709_Q
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/caixa-postal.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Caixa Postal
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Receber mensagens eletrônicas enviadas pela Receita Federal. Existem dois tipos de mensagens: mensagens de interesse geral e mensagens de interesse específico do detentor da Caixa Postal.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
  <segmento-da-sociedade>
   <id>
    empresas
   </id>
   <nome>
    Empresas
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida></eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      https://cav.receita.fazenda.gov.br/eCAC/publico/login.aspx?sistema=00006
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/programa-bolsa-familia-pbf.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Programa Bolsa Família - PBF
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>O Bolsa Família é um programa que transfere renda diretamente para as famílias pobres como forma de garantir o direito à alimentação adequada, à educação e à saúde. As famílias extremamente pobres recebem um valor necessário para que cada membro da família ganhe no mínimo R$ 70,00. Ou seja, somado o valor do Bolsa Família e a renda desta família fica garantida uma renda por pessoa superior a R$ 70,00.

Para as famílias pobres que recebem entre R$ 70,01 e R$ 140,00 o Bolsa Família repassa uma bolsa para cada criança, jovem, gestante ou nutriz. Para continuar a receber o benefício do Bolsa, a família deve manter as crianças e adolescentes na escola, assim como manter em dia o calendário de vacinação dos filhos de até 7 (sete) anos. As mulheres grávidas precisam fazer as consultas do pré-natal e as mães que estão amamentando (nutrizes) devem continuar o acompanhamento da sua saúde e da saúde do bebê.

Para receber o Bolsa Família tem que se inscrever no Cadastro Único e quem recebe tem que atualizar suas informações no Cadastro Único a cada dois anos ou sempre que houver alguma mudança na situação da família. O Bolsa Família é repassado através de cartão magnético preferencialmente para as mães.

* [Neste site você pode localizar o CRAS mais perto de sua residência. Esses dados podem ser localizados no mapa, basta escolher o seu Estado e o seu Município.](http://aplicacoes.mds.gov.br/sagi/FerramentasSAGI/Mops/)
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    previdencia-social
   </id>
   <area>Previdência Social</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    familia
   </id>
   <nome>
    Família
   </nome>
  </evento-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    apoio-financeiro-e-credito
   </id>
   <nome>
    Apoio financeiro e crédito
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Presencial" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   ministerio-do-desenvolvimento-social-e-combate-a-fome-mds
  </id>
  <nome>
   Ministério do Desenvolvimento Social e Combate à Fome (MDS)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/declaracao-de-capitais-brasileiros-no-exterior.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Declaração de Capitais Brasileiros no Exterior
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Página em que o cidadão pode declarar os bens e valores que possuir no exterior.

Devem declarar, todo ano, todos os residentes no País detentores de bens e valores fora do território nacional, que totalizem montante igual ou superior ao equivalente US$100.000,00 (cem mil dólares dos Estados Unidos).

Para aqueles que possuem bens de valor total igual ou superior a US$100.000.000,00 (cem milhões de dólares dos Estados Unidos), a declaração deve ser feita trimestralmente.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade></segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    viagem-ao-exterior
   </id>
   <nome>
    Viagem ao exterior
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://www4.bcb.gov.br/rex/CBE/Port/cbe.asp
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   banco-central-do-brasil-bcb
  </id>
  <nome>
   Banco Central do Brasil (BCB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/consulta-participacao-no-acompanhamento-diferenciado.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Consulta Participação no Acompanhamento Diferenciado
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>Consultar histórico de participação no acompanhamento econômico-tributário diferenciado e especial. Esta consulta permite a todos os contribuintes pessoas jurídicas, diferenciadas ou não, realizarem consulta ao histórico de sua participação no acompanhamento econômico-tributário diferenciado de que trata a Portaria Receita Federal nº 2.356, de 14 de dezembro de 2010.


 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    economia-e-financas
   </id>
   <area>Economia e Finanças</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    empresas
   </id>
   <nome>
    Empresas
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    contas-e-impostos
   </id>
   <nome>
    Contas e Impostos
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      https://cav.receita.fazenda.gov.br/eCAC/publico/login.aspx?sistema=00074
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-da-receita-federal-do-brasil-rfb
  </id>
  <nome>
   Secretaria da Receita Federal do Brasil (RFB)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>

=== servicosgoval/cartas-de-servico/backup/v2/servicos/consulta-a-situacao-dos-voos.xml
<?xml version="1.0" encoding="UTF-8"?>
<servico versao="2" xmlns="http://servicos.gov.br/cartas-servico/v2/schema/servico" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://servicos.gov.br/cartas-servico/v2/schema/servico ../servico.xsd">
 <nome>
  Consulta à Situação dos Voos
 </nome>
 <nomes-populares>
 </nomes-populares>
 <descricao>O Infraero Voos Online é uma ferramenta que consolida informações dos principais aeroportos brasileiros a respeito da situação atual de seu voo. Ela possibilita o rastreio de status dos voos em tempo quase real.

Além de consultar os horários de partidas e chegadas de voos, você também pode saber qual a distância de onde você está até o aeroporto para onde precisa ir e a previsão do tempo na cidade onde fica o aeroporto.

Consulte, antes de sair de casa, para descobrir se seu voo está no horário. Acesse a partir do website dedicado ou por meio de aplicativos mobile (Android e Iphone/Ipad).

* [Aplicativo mobile para a plataforma Android](https://play.google.com/store/apps/details?id=br.gov.infraero&amp;hl=pt_BR)
* [Aplicativo mobile para a plataforma Apple](https://itunes.apple.com/br/app/infraero-voos-online/id412206183?mt=8)
* [Consulte, também, a informação atualizada do número de atrasos e cancelamentos nos aeroportos operados pela Infraero.](http://www.infraero.gov.br/index.php/br/situacao-dos-voos/por-aeroporto.html)
 </descricao>
 <palavras-chave>
 </palavras-chave>
 <areas-de-interesse>
  <area-de-interesse>
   <id>
    trabalho
   </id>
   <area>Trabalho</area>
  </area-de-interesse>
 </areas-de-interesse>
 <segmentos-da-sociedade>
  <segmento-da-sociedade>
   <id>
    cidadaos
   </id>
   <nome>
    Cidadãos
   </nome>
  </segmento-da-sociedade>
 </segmentos-da-sociedade>
 <eventos-da-linha-da-vida>
  <evento-da-linha-da-vida>
   <id>
    viagem-ao-exterior
   </id>
   <nome>
    Viagem ao exterior
   </nome>
  </evento-da-linha-da-vida>
 </eventos-da-linha-da-vida>
 <legislacao-relacionada></legislacao-relacionada>
 <solicitantes></solicitantes>
 <etapas>
  <etapa>
   <titulo>
   </titulo>
   <descricao>
   </descricao>
   <documentos></documentos>
   <custos excecoes="false">
    <custo>
     <descricao>
     </descricao>
     <valor>
     </valor>
    </custo>
   </custos>
   <canais-de-prestacao>
    <canal-de-prestacao tipo="Web" preferencial="true">
     <titulo>
     </titulo>
     <referencia>
      http://voos.infraero.gov.br/voos/index.aspx
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Agendamento" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
    <canal-de-prestacao tipo="Aplicativo móvel" preferencial="false">
     <titulo>
     </titulo>
     <referencia>
     </referencia>
    </canal-de-prestacao>
   </canais-de-prestacao>
  </etapa>
 </etapas>
 <orgao>
  <id>
   secretaria-de-aviacao-civil-sac
  </id>
  <nome>
   Secretaria de Aviação Civil (SAC)
  </nome>
 </orgao>
 <situacao>
 </situacao>
</servico>
